*
This php file has two jobs. First, it sets the default port used by our server
to 8000.

Second, it makes some small syntax changes to the message generated by the erlserver
before it is sent back to the client. These changes took to long to make on the
server module, so this work-around was devised.

*/

<?php
    $x = $_GET["x"];
	$y = $_GET["y"];
    $url = "http://hal2000.skip.chalmers.se:8000?x=".$x."&y=".$y;
    $r = file_get_contents($url);
	$r =  str_replace('\\"','"',$r);
	$r =  str_replace('""','"',$r);
	$r =  str_replace('["','[',$r);
	$r =  str_replace('"]',']',$r);
    echo $r;

/*
{
   "X":[
      {
         "tag":"Kai",
         "freq":"<?php echo(rand(0,40));?>"
      },
      {
         "tag":"Dog",
         "freq":"<?php echo(rand(0,40));?>"
      },
      {
         "tag":"Fish",
         "freq":"<?php echo(rand(0,40));?>"
      }
   ],
   "Y":[
		{
         "tag":"Fish",
         "freq":"<?php echo(rand(0,40));?>"
		},
      {
         "tag":"Kai",
         "freq":"<?php echo(rand(0,40));?>"
      },
      {
         "tag":"Dog",
         "freq":"<?php echo(rand(0,40));?>"
      },
      {
         "tag":"Clown",
         "freq":"<?php echo(rand(0,40));?>"
      }
   ]
}
*/
?>